(TRADUZA ESSES TEXTOS E MANDE PARA MIM NO DISCORD)

"Faz um Anuncio"
"Faz um Soteio"
"Bani um Membro"
"Bani e Desbani um Membro"
"Desbani um Membro"
"Expulsa um Membro"
"Faz uma Embed"
"Ve todos os servidores onde o bot está"
"Reporta um Membro"
"Faz um bot enviar tal mensagem"
"Faz um Radio Moderação (recomendado um conal chamado Radio Moderação"
"Avisa um Membro"
"Faz uma Sugestão"
"Faz uma Sugestão pro Bot"
"Limpa o Chat"
"Piada"
"Resposta Aleatoria"
"Numero Aleatorio"
"Da um Kamehameha em alguem"
"Faz uma Conquista do Minecraft"
"gay"

"anunciar"
"sorteio"
"analisesugest"
"aprovarsugest"
"desaprovarsugest"
"cancelarsugest"
"ajuda"
"botinfo"
"creditos"
"prefixo"
"convite"
"invite"
"avatar"
"clear"
"abraçar"
"ecsede" (ec significa: estou com. então se for ingles pode ser iaw que é i am with)
"ecfome" (a mesma coisa do ecsede)
"embed"
"quente"
"frio"
"gay"
"guild"
"mcconquista" (pode deixar o mc porque significa minecraft)
"numeror" (o r no final significa random no caso: aleatório. se quiser pode trocar pode trocar se não quiser, ai é com vc)
"odeiotyran" (o tyran pode deixar)
"pedra"
"pacu"
"vender"
"warn"
"unwarn"
"mute"
"unmute"
"ban"
"softban"
"unban"
"kick"
"sugestao"
"sugestaobot"
"report"
"server"
"say"
"que"
"ping"


"Você não mencionou ninguém!"
"abraçou"
"SUGESTÃO EM ANALISE!"
"SUGESTÃO APROVADA!"
"SUGESTÃO DESAPROVADA!"
"NÃO ESTAMOS ACEITANDO SUGESTÕES NO MOMENTO!"
"Você não tem **permissão** para executar este comando!"
"Você não digitou o titulo! use o formato **C!anunciar <titulo> / <anuncio>**"
"Anuncio feito por"
"**Seu** avatar "
" Avatar de "
"Membro não identificado! Mencione um membro válido."
"Eu não posso banir esse membro, ele pode ter um cargo maior que o meu."
"Eu não posso kickar esse membro, ele pode ter um cargo maior que o meu."
"Banido!"
"Membro Banido:"
"Banido por:"
"Motivo:"
"Desculpe ${message.author} não pude banir o membro devido o: ${error}" (não precisa traduzir o ${message.author} nem o ${error})
"Olá! Meu Prefixo é C!"
"Olá meu nome é Charles e eu fui criado por Tyran#8501, o meu servidor de origem e o Panqueca's Lake, eu não tinha muitos comandos, mais surgiram 3 pessoas querendo ajudar o meu Desenvolvimento, que foram Junior Schueller, ZoriaTv_ e YuriHank. Pelo oque eu sei (não estou afirmando) o Junior Schueller foi oque mais fez comandos para mim. (em breve mais informações) (Panqueca's Lake: https://discord.gg/n4v7cYt"
"Por Favor Digite uma quantidade para limpar."
"Erro! você pode excluir apenas entre 2 e 100 mensagens de uma vez !"
"Convite do Servidor"
"**Link de Convite Permanente:**"
"Convite do Bot"
"**Link de Convite do Bot:**"
"Erro Encontrado! Este Erro foi mandado para para o Command Maker Log!"
"Oh Não! Um Erro foi encontrado ao Criar um Convite!"
"Meu Criador:"
"Meus Command Makers:"
" então pede um iFood!"
" ai você me pegou hein!"
"Já sei!"
"Então pede um iDrink!"
"Forneça algum conteúdo."
" Aqui ta congelado 3 graus"
" Eu não sou você é?"
"Pessoas:"
"Nome:"
" deu nota  !!"
" usou um kamehameha em "
"Erro"
"Você não colocou a descrição!"
